### ISSUE TITLE
[BUG] Switching between 2D and 3D frequently switches the animal currently displayed

### ISSUE THREAD

**Issue by NightMachinery** [duhaime/umap-zoo#1]
1. Choose 2D.
2. Go to the next animal.
3. Choose 3D.
4. Choose 2D.
5. The animal has changed.

This happens frequently.

**Comment by duhaime** [comment]
Thanks @NightMachinary ! Possibly there's a race condition in the ajax requests? It should be easy to resolve if you'd want to give it a go! Else I can try to take a look when time permits. 

Update: I thought I'd take a quick look before responding, and I can't reproduce this behavior :/ If you could add a little recording or more details of your browser and interaction patterns used to transition elements (mouse/keyboard keys) I can try to peer a little more closely...

**Comment by NightMachinery** [comment]
I have zero experience with AJAX (and generally little experience in web dev), so I would need a lot of handholding to be able to fix that. 

Race conditions seem a reasonable hypothesis to me, as my Internet connection is rather unstable. (I use VPNs optimized for non-detectability, and even without those, Iran’s networks aren’t as well oiled as Western ones.)

Overall, I thought the bug would be “obvious” to fix. I guess just leaving it be is better. The site is still usable with the bug.

**Comment by duhaime** [comment]
Oh I'm sure it wouldn't take much doing, just time is tight at the moment :)
